# Generated by Django 3.2.8 on 2021-11-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consumer'),
        ),
        migrations.AlterField(
            model_name='store',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.provider'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
