# Generated by Django 3.2.8 on 2022-04-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20220331_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ammount',
            new_name='amount',
        ),
    ]
