# Generated by Django 3.2.8 on 2022-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
